name: "godot gut ci test"
on: push

jobs:
  gut-godot4:
    name: Run GUT tests for Godot 4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot GUT CI Test
        uses: ./
        with:
          godot_version: 4.2
          gut_params: -gdir=res://test/unit
          # project_path: gut-ci-test-project/godot4

  # gut-godot42:
  #   name: Run GUT tests for Godot 4
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Godot GUT CI Test
  #       uses: ./
  #       with:
  #         godot_version: 4.2
  #         gut_params: -gdir=res://tests/unit
  #         project_path: gut-ci-test-project/godot4
